# Site settings
title: Notes by Jules Jacobs
email: julesjacobs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julesjacobs.github.io" # the base hostname & protocol for your site
github_username: julesjacobs

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
