import { unsupportedSamples } from "./unsupported_samples.js";

export const topicOrder = [
  "Warm-up",
  "Labeled Tuples",
  "Locality & Stack Allocation",
  "Let Mutable",
  "Polymorphic Parameters & GADTs",
  "Module Extensions",
];

export const supportedSamples = [
  {
    id: "warmup-hello",
    topic: "Warm-up",
    label: "Hello",
    filename: "hello.ml",
    mode: "run",
    source: [
      "let greeting = \"hello from oxcaml\";;",
      "print_endline greeting;;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "hello from oxcaml\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "warmup-type-error",
    topic: "Warm-up",
    label: "Type error",
    filename: "type_error.ml",
    mode: "check",
    source: "let message : string = 41 + 1\n",
    expected_kind: "diagnostic",
    expected_text: [
      "Error:",
      "expected of type",
      "string",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "warmup-runtime-exception",
    topic: "Warm-up",
    label: "Runtime exception",
    filename: "runtime_exception.ml",
    mode: "run",
    source: "raise (Failure \"boom\");;\n",
    expected_kind: "diagnostic",
    expected_text: [
      "Exception: Failure \"boom\".",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "labeled-tuples-sum-and-product",
    topic: "Labeled Tuples",
    label: "Sum and product",
    filename: "sum_and_product.ml",
    mode: "run",
    source: [
      "let sum_and_product ints =",
      "  let init = ~sum:0, ~product:1 in",
      "  List.fold_left (fun (~sum, ~product) elem ->",
      "    let sum = elem + sum in",
      "    let product = elem * product in",
      "    ~sum, ~product) init ints;;",
      "let ~sum, ~product = sum_and_product [2; 3; 4];;",
      "print_endline (string_of_int sum);;",
      "print_endline (string_of_int product);;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "9\n24\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/labeled-tuples.md",
  },
  {
    id: "labeled-tuples-swap",
    topic: "Labeled Tuples",
    label: "Swap by label",
    filename: "swap_by_label.ml",
    mode: "run",
    source: [
      "let point = ~x:20, ~y:22;;",
      "let swap (~x, ~y) = ~x:y, ~y:x;;",
      "let ~x, ~y = swap point;;",
      "print_endline (string_of_int (x + y));;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "42\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "labeled-tuples-partial-known-type",
    topic: "Labeled Tuples",
    label: "Partial pattern with known type",
    filename: "partial_pattern_known_type.ml",
    mode: "run",
    source: [
      "let lt = ~x:0, ~y:42;;",
      "let twice_y = let ~y, .. = lt in y * 2;;",
      "print_endline (string_of_int twice_y);;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "84\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/labeled-tuples.md",
  },
  {
    id: "labeled-tuples-unknown-partial-pattern",
    topic: "Labeled Tuples",
    label: "Unknown partial pattern error",
    filename: "unknown_partial_pattern.ml",
    mode: "check",
    source: [
      "let get_y t =",
      "  let ~y, .. = t in",
      "  y",
    ].join("\n"),
    expected_kind: "diagnostic",
    expected_text: [
      "Could not determine the type of this partial tuple pattern",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/labeled-tuples.md",
  },
  {
    id: "locality-stack-tuple-sum",
    topic: "Locality & Stack Allocation",
    label: "Stack tuple sum",
    filename: "stack_tuple_sum.ml",
    mode: "run",
    source: [
      "let sum () =",
      "  let local_ pair : int * int = stack_ (20, 22) in",
      "  let x, y = pair in",
      "  x + y;;",
      "print_endline (string_of_int (sum ()));;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "42\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "locality-local-argument",
    topic: "Locality & Stack Allocation",
    label: "Local argument",
    filename: "local_argument.ml",
    mode: "run",
    source: [
      "let bump (local_ x : int) = x + 1;;",
      "print_endline (string_of_int (bump 41));;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "42\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "locality-local-return-with-exclave",
    topic: "Locality & Stack Allocation",
    label: "Local return with exclave",
    filename: "local_return_with_exclave.ml",
    mode: "run",
    source: [
      "let g () : int @ local = exclave_ 42;;",
      "print_endline (string_of_int (g ()));;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "42\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/app.js (legacy sample)",
  },
  {
    id: "locality-stack-return-needs-exclave",
    topic: "Locality & Stack Allocation",
    label: "Stack return needs exclave",
    filename: "stack_return_needs_exclave.ml",
    mode: "check",
    source: "let f () = stack_ (3, 5)\n",
    expected_kind: "diagnostic",
    expected_text: [
      "function return value",
      "Use exclave_ to return a local value",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-modes/stack.ml",
  },
  {
    id: "locality-local-return-escape-error",
    topic: "Locality & Stack Allocation",
    label: "Local return escape error",
    filename: "local_return_escape_error.ml",
    mode: "check",
    source: "let add a b @ local = local_ (a + b)\n",
    expected_kind: "diagnostic",
    expected_text: [
      "function return value",
      "Use exclave_ to return a local value",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-modes/modes.ml",
  },
  {
    id: "locality-local-tail-call-error",
    topic: "Locality & Stack Allocation",
    label: "Local tail-call error",
    filename: "local_tail_call_error.ml",
    mode: "run",
    source: [
      "let show () =",
      "  let local_ message = \"hello locality\" in",
      "  Stdlib.print_endline message;;",
      "show ();;",
    ].join("\n"),
    expected_kind: "diagnostic",
    expected_text: [
      "argument in a tail call",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "experiments/web_bytecode/tmp_examples_probe.html",
  },
  {
    id: "let-mutable-loop-accumulator",
    topic: "Let Mutable",
    label: "Loop accumulator",
    filename: "let_mutable_loop_accumulator.ml",
    mode: "run",
    source: [
      "let sum n =",
      "  let mutable acc = 0 in",
      "  for i = 1 to n do",
      "    acc <- acc + i",
      "  done;",
      "  acc;;",
      "print_endline (string_of_int (sum 10));;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "55\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-local/let_mutable.ml",
  },
  {
    id: "let-mutable-nested-record-update",
    topic: "Let Mutable",
    label: "Nested record update",
    filename: "let_mutable_nested_record_update.ml",
    mode: "run",
    source: [
      "type state = { text : string ref };;",
      "let final_text =",
      "  let mutable value = { text = ref \"Hi\" } in",
      "  value <- { text = ref \"Bye\" };",
      "  !(value.text);;",
      "print_endline final_text;;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "Bye\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-local/let_mutable.ml",
  },
  {
    id: "let-mutable-closure-capture-error",
    topic: "Let Mutable",
    label: "Closure capture error",
    filename: "let_mutable_closure_capture_error.ml",
    mode: "check",
    source: [
      "let sum n =",
      "  let mutable acc = 0 in",
      "  let add () = acc <- acc + n in",
      "  add ()",
    ].join("\n"),
    expected_kind: "diagnostic",
    expected_text: [
      "Mutable variable cannot be used inside a function",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-local/let_mutable.ml",
  },
  {
    id: "let-mutable-lazy-capture-error",
    topic: "Let Mutable",
    label: "Lazy capture error",
    filename: "let_mutable_lazy_capture_error.ml",
    mode: "check",
    source: [
      "let delayed =",
      "  let mutable x = 42 in",
      "  lazy (x + 1)",
    ].join("\n"),
    expected_kind: "diagnostic",
    expected_text: [
      "Mutable variable cannot be used inside a lazy expression",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "testsuite/tests/typing-local/let_mutable.ml",
  },
  {
    id: "poly-gadt-locally-abstract-printer",
    topic: "Polymorphic Parameters & GADTs",
    label: "Locally abstract GADT printer",
    filename: "locally_abstract_gadt_printer.ml",
    mode: "run",
    source: [
      "type _ shape = Int : int shape | Bool : bool shape;;",
      "let show (type a) (s : a shape) (x : a) =",
      "  match s with",
      "  | Int -> string_of_int x",
      "  | Bool -> string_of_bool x;;",
      "print_endline (show Int 42);;",
      "print_endline (show Bool true);;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "42\ntrue\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "manual/src/tutorials/gadtexamples.etex",
  },
  {
    id: "poly-gadt-polymorphic-parameter-builder",
    topic: "Polymorphic Parameters & GADTs",
    label: "Polymorphic parameter record builder",
    filename: "polymorphic_parameter_record_builder.ml",
    mode: "run",
    source: [
      "type t = { a : string; b : int };;",
      "type _ field = A : string field | B : int field;;",
      "let create (f : 'a. 'a field -> 'a) = { a = f A; b = f B };;",
      "let forty_two (type a) : a field -> a = function",
      "  | A -> \"forty two\"",
      "  | B -> 42;;",
      "let result = create forty_two;;",
      "print_endline result.a;;",
      "print_endline (string_of_int result.b);;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "forty two\n42\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/polymorphic-parameters.md",
  },
  {
    id: "poly-gadt-missing-polymorphic-annotation",
    topic: "Polymorphic Parameters & GADTs",
    label: "Missing polymorphic annotation error",
    filename: "missing_polymorphic_annotation.ml",
    mode: "check",
    source: [
      "type t = { a : string; b : int }",
      "type _ field = A : string field | B : int field",
      "let create f = { a = f A; b = f B }",
    ].join("\n"),
    expected_kind: "diagnostic",
    expected_text: [
      "int field",
      "string field",
    ],
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/polymorphic-parameters.md",
  },
  {
    id: "module-extensions-include-functor-structure",
    topic: "Module Extensions",
    label: "Include functor in structure",
    filename: "include_functor_structure.ml",
    mode: "run",
    source: [
      "module F (T : sig type t val show : t -> string end) = struct",
      "  let show_twice x = T.show x ^ \", \" ^ T.show x",
      "end;;",
      "module M = struct",
      "  type t = int",
      "  let show = string_of_int",
      "  include functor F",
      "end;;",
      "print_endline (M.show_twice 21);;",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "21, 21\n",
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/include-functor.md",
  },
  {
    id: "module-extensions-include-functor-signature",
    topic: "Module Extensions",
    label: "Include functor in signature",
    filename: "include_functor_signature.ml",
    mode: "check",
    source: [
      "module type F =",
      "  functor (T : sig type t val show : t -> string end) ->",
      "    sig val show_twice : T.t -> string end",
      "",
      "module type S = sig",
      "  type t",
      "  val show : t -> string",
      "  include functor F",
      "end",
    ].join("\n"),
    expected_kind: "success",
    expected_text: "",
    browser_status: "supported",
    local_status: "verified",
    origin: "jane/doc/extensions/_11-miscellaneous-extensions/include-functor.md",
  },
];

export const allSamples = [...supportedSamples, ...unsupportedSamples];
export const visibleSamples = supportedSamples.filter(
  (sample) => sample.browser_status === "supported",
);

const sampleMap = new Map(allSamples.map((sample) => [sample.id, sample]));

export function getSampleById(sampleId) {
  return sampleMap.get(sampleId) ?? null;
}

export function getVisibleSamplesByTopic() {
  return topicOrder
    .map((topic) => ({
      topic,
      samples: visibleSamples.filter((sample) => sample.topic === topic),
    }))
    .filter((group) => group.samples.length > 0);
}

export function matchesExpectedText(actual, expectedText) {
  if (Array.isArray(expectedText)) {
    return expectedText.every((snippet) => actual.includes(snippet));
  }
  return actual === expectedText;
}

export const defaultSampleId = "labeled-tuples-sum-and-product";
export const defaultSample = getSampleById(defaultSampleId);
