name: Check website build
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: website-preview
          path: _site/
          retention-days: 3
